### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dest'

### ISSUE THREAD

**Issue by Raviu56** [RPISEC/llvm-deobfuscator#8]
Plugin fails on binary ninja 2.0.x
I was simply looking at InSpectre https://www.grc.com/files/InSpectre.exe

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\user\Desktop\BinaryNinja\BinaryNinja-Windows\plugins\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Users\user\Desktop\BinaryNinja\BinaryNinja-Windows\plugins\..\python\binaryninja\plugin.py", line 731, in run
    self.task.run()
  File "C:\Users\user\AppData\Roaming\Binary Ninja\plugins\llvm-deobfuscator\__init__.py", line 18, in run
    self.func(bv, self.addr)
  File "C:\Users\user\AppData\Roaming\Binary Ninja\plugins\llvm-deobfuscator\deflatten.py", line 295, in deflatten_cfg
    state_var = func.get_low_level_il_at(addr).medium_level_il.dest
AttributeError: 'NoneType' object has no attribute 'dest'
```

**Comment by stevemk14ebr** [comment]
I also sometimes get:
```
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "C:\Users\steve\AppData\Local\Vector35\BinaryNinja\plugins\..\python\binaryninja\plugin.py", line 731, in run
    self.task.run()
  File "C:\Users\steve\AppData\Roaming\Binary Ninja\plugins\llvm-deobfuscator-master\__init__.py", line 18, in run
    self.func(bv, self.addr)
  File "C:\Users\steve\AppData\Roaming\Binary Ninja\plugins\llvm-deobfuscator-master\deflatten.py", line 298, in deflatten_cfg
    backbone = compute_backbone_map(bv, mlil, state_var)
  File "C:\Users\steve\AppData\Roaming\Binary Ninja\plugins\llvm-deobfuscator-master\deflatten.py", line 143, in compute_backbone_map
    cond_var = bb[-1].condition.src
AttributeError: 'MediumLevelILInstruction' object has no attribute 'src'

```

**Comment by WYK15** [comment]
I also got this
